const age=80;
console.log(age);
console.log(typeof age);
let fullName="ritik kumar";
console.log(fullName);
console.log(typeof fullName);
let name=null;
console.log(name);
console.log(typeof name);
let a=undefined;
console.log(a);
console.log(typeof a);
isPass=true;
console.log(isPass);
console.log(typeof isPass);
console.log(+true);
console.log(typeof +true);
console.log(+false);
console.log(typeof +false); 